CREATE TABLE IF NOT EXISTS tasks (
    num_tasks INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre_tasks VARCHAR(255) NOT NULL,
    status_tasks VARCHAR(20) NOT NULL,
    assignee VARCHAR(50)
);

-- Pour une base déjà créée (ex. Neon) : met le schéma à niveau sans perdre les données
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS assignee VARCHAR(50);
ALTER TABLE tasks ALTER COLUMN titre_tasks TYPE VARCHAR(255);

-- Données fictives : prénoms inventés
INSERT INTO tasks (titre_tasks, status_tasks, assignee)
SELECT 'Preparer les paniers', 'Pending', 'Zorali'
WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE titre_tasks = 'Preparer les paniers');
INSERT INTO tasks (titre_tasks, status_tasks, assignee)
SELECT 'Trier les livres', 'Completed', 'Mivren'
WHERE NOT EXISTS (SELECT 1 FROM tasks WHERE titre_tasks = 'Trier les livres');
